# roles/static-ip/handlers/main.yml
---
-   name: Reboot
    become: true
    reboot:
        post_reboot_delay: 10 
        test_command: whoami
        reboot_timeout: 600 
        msg: Reboot initiated by Ansible
        connect_timeout: 600

-   name: Wait for reboot to finish
    become: false
    wait_for:
        timeout: 600
        delay: 10
        port: 22
    delegate_to: localhost

-   name: Create a (non default) user account
    become: true
    user:
        name: "{{ username }}"
        shell: /bin/bash
        createhome: yes
        comment: "{{ comment }}"
        groups: docker
        password: "{{ password }}"